#TS_SESSION_COMMANDS=("(cd /opt/hpotter && nvim .)" "(cd /opt/hpotter && /bin/zsh)" "(cd /opt/hpotter && tail -F -n100 hpotter.log)" "cd /opt/hpotter/containers/ && nvim .")
#TS_SESSION_COMMANDS=("(cd /opt/do/interview/coding && nvim .)" "(cd /opt/do/interview/coding && /bin/zsh)")
#TS_SESSION_COMMANDS=("(cd /opt/interview && nvim .)" "(cd /opt/interview && /bin/zsh)" "(cd /opt/interview && /bin/zsh)" "(cd /opt/interview && /bin/zsh)" "(cd /opt/interview && /bin/zsh)")
TS_SESSION_COMMANDS=("(cd /opt/rust/hpotter && nvim .)" "(cd /opt/rust/hpotter && /bin/zsh)" "(cd /opt/rust/hpotter && /bin/zsh)")
TS_SEARCH_PATHS=(/)
TS_MAX_DEPTH=2
